--------------------------------------------------------
--  File created - Saturday-May-11-2024   
--------------------------------------------------------
alter session set "_oracle_script"=true;
CREATE USER BIBLIOTECARIO IDENTIFIED BY "BIBLIOTECARIO";

GRANT CREATE SESSION TO BIBLIOTECARIO;
GRANT CREATE TABLE TO BIBLIOTECARIO;
GRANT DELETE ANY TABLE, UPDATE ANY TABLE, INSERT ANY TABLE TO BIBLIOTECARIO;
GRANT CREATE PROCEDURE TO BIBLIOTECARIO;
GRANT CREATE SEQUENCE TO BIBLIOTECARIO;
ALTER USER BIBLIOTECARIO QUOTA UNLIMITED ON users;
GRANT CONNECT TO BIBLIOTECARIO;
--------------------------------------------------------
--  DDL for Table AUTOR
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."AUTOR" 
   (	"ID_AUTOR" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_AUTOR" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BIBLIOTECA_MATERIAL
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" 
   (	"CANTIDAD" NUMBER(10,0), 
	"ID_AUTOR" NUMBER(19,0), 
	"ID_IDIOMA" NUMBER(19,0), 
	"ID_MATERIAL_BIBLIOTECA" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(255 CHAR), 
	"TITULO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IDIOMA
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."IDIOMA" 
   (	"ID_IDIOMA" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_IDIOMA" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIBRO
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."LIBRO" 
   (	"ES_OBRA_DE_REFERENCIA" NUMBER(1,0), 
	"ID_MATERIAL" NUMBER(19,0), 
	"ISBN" VARCHAR2(255 CHAR), 
	"LOGO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIALES_MIEMBROS
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."MATERIALES_MIEMBROS" 
   (	"MATERIAL_MIEMBRO" NUMBER(19,0), 
	"CARNET_MIEMBRO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MIEMBRO
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."MIEMBRO" 
   (	"PENALIZADO" NUMBER(1,0), 
	"ID_USUARIO" NUMBER(19,0), 
	"CARNET" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MORA
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."MORA" 
   (	"COSTO_PRESTAMO" FLOAT(126) DEFAULT 2.50, 
	"MORA_PRESTAMO" FLOAT(126) DEFAULT 0.00, 
	"ID_MORA" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CARNET_MIEMBRO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRESTA
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."PRESTA" 
   (	"ESTA_ACTIVO" NUMBER(1,0) DEFAULT 1, 
	"FECHA_PRESTAMO" TIMESTAMP (6), 
	"FECHA_RETORNO" TIMESTAMP (6), 
	"ID_MATERIAL" NUMBER(19,0), 
	"ID_MORA" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."ROL" 
   (	"ID_ROL" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_ROL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "BIBLIOTECARIO"."USUARIO" 
   (	"ID_USUARIO" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CORREO" VARCHAR2(255 CHAR), 
	"NOMBRE_USUARIO" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"ID_ROL" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure FINDBYUSERNAME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BIBLIOTECARIO"."FINDBYUSERNAME" (
    p_username IN usuario.username%TYPE
)
AS
BEGIN
     SELECT * FROM usuario WHERE username = p_username;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETIDMORA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BIBLIOTECARIO"."GETIDMORA" 
(carnet in mora.carnet_miembro%TYPE, id_mora_out out mora.id_mora%TYPE)
AS
BEGIN
    SELECT id_mora INTO id_mora_out FROM MORA WHERE MORA.CARNET_MIEMBRO = carnet;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTARMORA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BIBLIOTECARIO"."INSERTARMORA" (
    carnet IN mora.carnet_miembro%TYPE,
    id_mora_out OUT mora.id_mora%TYPE
)
AS
BEGIN
    -- Insertar el registro en la tabla MORA y obtener su ID de inserción
    INSERT INTO MORA (CARNET_MIEMBRO) 
    VALUES (carnet)
    RETURNING id_mora INTO id_mora_out;

    COMMIT; -- Realizar la confirmación de la transacción
END;

/
--------------------------------------------------------
--  DDL for Procedure LISTADELIBROSPORAUTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BIBLIOTECARIO"."LISTADELIBROSPORAUTOR" 
(
nombreAutor IN autor.nombre_autor%TYPE,
CURSOR_ IN OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CURSOR_ FOR
        SELECT bm.titulo,bm.descripcion,a.nombre_autor
        FROM biblioteca_material bm INNER JOIN autor a
        ON bm.id_autor=a.id_autor
        WHERE LOWER(a.nombre_autor) LIKE nombreAutor ;--Thomas Harris
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARPRESTAMOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BIBLIOTECARIO"."REGISTRARPRESTAMOS" (
    carnet IN mora.carnet_miembro%TYPE,
    id_material_nuevo IN presta.id_material%TYPE
) 
AS
    id_mora_out mora.id_mora%TYPE; -- Variable para almacenar el resultado de getIdMora
BEGIN
    -- Insertar en MATERIALES_MIEMBROS
    INSERT INTO MATERIALES_MIEMBROS (CARNET_MIEMBRO, MATERIAL_MIEMBRO) VALUES (carnet, id_material_nuevo);

    -- Insertar en MORA
    --INSERT INTO MORA (CARNET_MIEMBRO) VALUES (carnet);
    insertarMora(carnet,id_mora_out);

    -- Obtener id_mora usando getIdMora
    --getIdMora(carnet, id_mora_out);

    -- Insertar en presta
    INSERT INTO presta (id_material, id_mora, fecha_prestamo, fecha_retorno) 
    VALUES (id_material_nuevo, id_mora_out, TO_DATE('2024-06-12','yyyy-MM-DD'), TO_DATE('2024-06-14','yyyy-MM-DD'));
END;

/
--------------------------------------------------------
--  Constraints for Table PRESTA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."PRESTA" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."PRESTA" MODIFY ("ID_MORA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."PRESTA" ADD CHECK (esta_activo in (0,1)) ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."PRESTA" ADD PRIMARY KEY ("ID_MATERIAL", "ID_MORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTOR
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."AUTOR" MODIFY ("ID_AUTOR" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."AUTOR" MODIFY ("NOMBRE_AUTOR" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."AUTOR" ADD PRIMARY KEY ("ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IDIOMA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."IDIOMA" MODIFY ("ID_IDIOMA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."IDIOMA" MODIFY ("NOMBRE_IDIOMA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."IDIOMA" ADD PRIMARY KEY ("ID_IDIOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MORA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."MORA" MODIFY ("COSTO_PRESTAMO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MORA" MODIFY ("MORA_PRESTAMO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MORA" MODIFY ("ID_MORA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MORA" ADD PRIMARY KEY ("ID_MORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BIBLIOTECA_MATERIAL
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" MODIFY ("ID_MATERIAL_BIBLIOTECA" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" ADD PRIMARY KEY ("ID_MATERIAL_BIBLIOTECA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIALES_MIEMBROS
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."MATERIALES_MIEMBROS" MODIFY ("MATERIAL_MIEMBRO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MATERIALES_MIEMBROS" MODIFY ("CARNET_MIEMBRO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MATERIALES_MIEMBROS" ADD PRIMARY KEY ("MATERIAL_MIEMBRO", "CARNET_MIEMBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."USUARIO" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MIEMBRO
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."MIEMBRO" MODIFY ("PENALIZADO" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MIEMBRO" MODIFY ("CARNET" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."MIEMBRO" ADD CHECK (penalizado in (0,1)) ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."MIEMBRO" ADD PRIMARY KEY ("CARNET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."MIEMBRO" ADD UNIQUE ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."ROL" ADD PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBRO
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."LIBRO" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "BIBLIOTECARIO"."LIBRO" ADD CHECK (es_obra_de_referencia in (0,1)) ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."LIBRO" ADD PRIMARY KEY ("ID_MATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BIBLIOTECA_MATERIAL
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" ADD CONSTRAINT "FKAY015VE2LC8KDFXBU3M9JWFG7" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "BIBLIOTECARIO"."AUTOR" ("ID_AUTOR") ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" ADD CONSTRAINT "FKBVJ5XR3OCQDVSRERXG0XOI4PG" FOREIGN KEY ("ID_IDIOMA")
	  REFERENCES "BIBLIOTECARIO"."IDIOMA" ("ID_IDIOMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIBRO
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."LIBRO" ADD CONSTRAINT "FK10K51HJQDCNFYQDFDMIP9IR63" FOREIGN KEY ("ID_MATERIAL")
	  REFERENCES "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" ("ID_MATERIAL_BIBLIOTECA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIALES_MIEMBROS
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."MATERIALES_MIEMBROS" ADD CONSTRAINT "FKMITPK86R34CA6ACD1VV9M0HO5" FOREIGN KEY ("MATERIAL_MIEMBRO")
	  REFERENCES "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" ("ID_MATERIAL_BIBLIOTECA") ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."MATERIALES_MIEMBROS" ADD CONSTRAINT "FK4SKOGJW4JLPOKT5WJ3YE261FS" FOREIGN KEY ("CARNET_MIEMBRO")
	  REFERENCES "BIBLIOTECARIO"."MIEMBRO" ("CARNET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MIEMBRO
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."MIEMBRO" ADD CONSTRAINT "FKIODC6J36TFSGDI6B4FO40AX6P" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "BIBLIOTECARIO"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MORA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."MORA" ADD CONSTRAINT "FKBGXTHEOIL69NINQ82QU9IRRA8" FOREIGN KEY ("CARNET_MIEMBRO")
	  REFERENCES "BIBLIOTECARIO"."MIEMBRO" ("CARNET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESTA
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."PRESTA" ADD CONSTRAINT "FKEMSXLHBVGWK4EWKOTP4SK7VI6" FOREIGN KEY ("ID_MATERIAL")
	  REFERENCES "BIBLIOTECARIO"."BIBLIOTECA_MATERIAL" ("ID_MATERIAL_BIBLIOTECA") ENABLE;
  ALTER TABLE "BIBLIOTECARIO"."PRESTA" ADD CONSTRAINT "FK5OMBFNF6IYQS8N0H7MW0E5RF9" FOREIGN KEY ("ID_MORA")
	  REFERENCES "BIBLIOTECARIO"."MORA" ("ID_MORA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "BIBLIOTECARIO"."USUARIO" ADD CONSTRAINT "FKMYV3138VVCI6KAQ3Y5KT4CNTU" FOREIGN KEY ("ID_ROL")
	  REFERENCES "BIBLIOTECARIO"."ROL" ("ID_ROL") ENABLE;
