version: '3.8'
services:
  server:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./nginxconfig/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginxconfig/logs:/code
  spring-app:
    build:
      context: ./dockerfiles
      dockerfile: java.dockerfile 
    volumes:
      - ./biblioteca:/code
#    ports:
#    - '8000:8080'
    depends_on:
      - oracle-db
  maven:
    build:
      context: ./dockerfiles
      dockerfile: maven.dockerfile
    volumes:
      - ./biblioteca:/app

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-biblioteca
    environment:
      - ORACLE_PWD=Oracle_123
    ports:
      - 1522:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-backup:
